apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
spec:
  template:
    spec:
      containers:
        - name: broadcaster
          env:
            - name: FORWARD_TO_EXTERNAL
              value: "true"
            - name: BROADCASTER_URL
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secret
                  key: BROADCASTER_URL
