apiVersion: v1
kind: Service
metadata:
  name: wikipedia
  namespace: exercises
  labels:
    app: wikipedia
spec:
  type: ClusterIP
  selector:
    app: wikipedia
  ports:
    - name: http
      port: 80
      targetPort: 80
