apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummysite-controller
  namespace: dummysite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummysite-controller
  template:
    metadata:
      labels:
        app: dummysite-controller
    spec:
      serviceAccountName: dummysite-controller
      containers:
        - name: controller
          image: msami936/dummysite-controller:5.1
          imagePullPolicy: Always
          env:
            - name: SERVICE_TYPE
              # Use LoadBalancer on GKE; ClusterIP + port-forward on k3d
              value: "ClusterIP"
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
