apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: todo-app:1.13
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "3000"
            - name: DATA_DIR
              value: /data
            - name: CACHE_MS
              value: "600000"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: todo-image-data
              mountPath: /data
      volumes:
        - name: todo-image-data
          persistentVolumeClaim:
            claimName: todo-image-pvc
