apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: ping-pong:1.11
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "3000"
            - name: COUNT_FILE
              value: /data/pong.txt
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-data
              mountPath: /data
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-pvc
