apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - namespace.yaml
  - configmaps.yaml
  - postgres.yaml
  - todo-app.yaml
  - todo-backend.yaml
  - cronjob-wiki-todo.yaml
  - cronjob-db-backup.yaml
