apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
  namespace: exercises
data:
  MESSAGE: hello world
  information.txt: |
    this text is from file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-generator
          image: msami936/log-output:4.1
          imagePullPolicy: Always
          command: ["node", "generator.js"]
          env:
            - name: LOG_FILE
              value: /shared/log.txt
          volumeMounts:
            - name: shared-log
              mountPath: /shared
        - name: log-reader
          image: msami936/log-output:4.1
          imagePullPolicy: Always
          command: ["node", "reader.js"]
          env:
            - name: PORT
              value: "3000"
            - name: LOG_FILE
              value: /shared/log.txt
            - name: PINGPONG_URL
              value: http://ping-pong/pings
            - name: INFO_FILE
              value: /config/information.txt
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 3
            failureThreshold: 1
          volumeMounts:
            - name: shared-log
              mountPath: /shared
            - name: log-output-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: shared-log
          emptyDir: {}
        - name: log-output-config
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt
---
apiVersion: v1
kind: Service
metadata:
  name: log-output
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
