apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - ../../base
  - ingress.yaml

images:
  - name: todo-app
    newName: msami936/todo-app
    newTag: "4.2"
  - name: todo-backend
    newName: msami936/todo-backend
    newTag: "4.2"
